
[[main]]
name = "Home"
url  = "/"
weight = 10

[[main]]
name = "Guides"
url  = "/guides/"
weight = 20

[[main]]
name = "Categories"
pageRef  = "categories"
weight = 30

[[main]]
name = "Tags"
pageRef = "tags"
weight = 40

[[main]]
name = "Legal"
url  = "/legal/"
weight = 99

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
